version: '3.7'

services:
  guides:
    container_name: guides
    image: jekyll/builder:4
    command: jekyll serve --config _config.yml,_config.dev.yml
    ports:
    - 4001:4000
    volumes:
    - $PWD:/srv/jekyll
